import { state } from './state.js';
import { chapterFiveChoices,chapterFiveScenes,finalActions,availableFinalActions,openingLabels,counselLines,theologicalArguments,theologicalAlternatives,reportFacts,debateArguments } from '../data/chapter-five.js';
import { deriveChapter5OpeningPath,resolveChapterFiveOutcomes,chapterSixHandoff } from '../data/chapter-five-state.js';
import { advanceDialogue,beginDialogue } from './dialogue-engine.js';
import { syncConsequences } from './consequences.js';
let hooks;
export function configureChapterFive(value){hooks=value;}
const l=(speaker,text)=>({speaker,text});
const go=s=>hooks.enterScene('ch5_'+s);
const c=()=>state.chapter5;
const talk=(lines,next='ready')=>beginDialogue(lines,'chapter-five',next);
export const endLabels={violent_defeat:'Der Haufen wurde zurückgedrängt',negotiation_collapsed:'Die Verhandlung ist abgebrochen',civilians_protected:'Menschen wurden aus der Gefahr gebracht',community_fragmented:'Die Gemeinde ist auseinandergegangen',fragile_deescalation:'Eine unsichere Ruhe'};
export const outcomeTexts={
 konrad:{safe:'Konrad ist zurück. Er blieb bei den anderen, bis der Rückweg frei war. Er fragt weiter, was aus euren Forderungen wird.',injured:'Konrad ist verletzt zurückgekommen. Er braucht Hilfe. Er hält die Forderungen weiter für berechtigt; über das Vorgehen will er nun neu sprechen.',captured:'Konrad ist festgenommen worden. Die Herrschaft macht seine Freilassung von weiteren Zusagen abhängig. Ihr müsst entscheiden, wer für ihn eintritt.',missing:'Konrad ist nicht zurück. Ein Zeuge sah ihn mit einer anderen Gruppe abbiegen. Ob er sicher ist, weiß hier niemand.'},
 negotiation:{partial_agreement:'Eine Teilvereinbarung liegt vor: ausgewählte Zusatzbelastungen werden vorläufig ausgesetzt, Vertreter dürfen wiederkommen. Die grundlegenden Forderungen bleiben offen.',open:'Ein Gesprächsweg ist geblieben. Es gibt noch keine verbindliche Zusage und keine Sicherheit, dass die nächste Abordnung gehört wird.',collapsed:'Der Gesprächsweg ist abgebrochen. Der Verwalter verlangt erst die Wiederherstellung seiner Verfügung; eure Forderungen sind damit nicht erledigt.'},
 civilian:{many_protected:'Viele Unbeteiligte konnten den Gefahrenbereich verlassen. Sie haben ihre Höfe zurückgelassen; Schutz bedeutete nicht, dass sie nichts verloren haben.',some_protected:'Einige Menschen fanden einen Rückweg oder Hilfe. Andere blieben im Gefahrenbereich, während eure Aufmerksamkeit anderswo gebraucht wurde.',high_exposure:'Viele Unbeteiligte blieben zwischen den Gruppen. Über ihre Sicherheit wurde entschieden, ohne dass sie alle mitsprechen konnten.'}
};
const functionLimits={hope:'Hoffnung kann tragen. Sie darf aber nicht das Versprechen ersetzen, Bedrohten jetzt zu helfen.',critique:'Die Kritik an Unrecht braucht auch Selbstkritik: Was richten unsere eigenen Mittel an?',community:'Gemeinschaft kann schützen. Sie darf Andersdenkende und Außenstehende nicht aus ihrer Verantwortung ausschließen.',resistance:'Gewissen kann Widerstand begründen. Daraus folgt nicht, dass jede Form des Widerstands erlaubt wäre.',limit:'Gewalt zu begrenzen bleibt nötig. Das darf jedoch nicht bedeuten, bestehendes Unrecht schweigend hinzunehmen.',legitimate:'Wer Gewalt unmittelbar zu Gottes Auftrag erklärt, kann die eigene Entscheidung der Kritik entziehen.'};
const functionNames={hope:'Hoffnung',critique:'Unrechtskritik',community:'Gemeinschaft',resistance:'Widerstand',limit:'Gewaltbegrenzung',legitimate:'Gewaltlegitimation'};
export function functionReflection(value){return 'Du hast '+value.strongest.map(id=>functionNames[id]).join(' und ')+' besonders wahrgenommen. '+functionLimits[value.dangerousWhenAbsolute];}
const lutherNames={freedom:'die Freiheit vor Gott',service:'den Dienst am Nächsten',order:'die weltliche Ordnung',revolt:'die Kritik des Aufruhrs'};
const lutherLimits={freedom:'Gottes Annahme muss nicht durch Leistung verdient werden. Sie entscheidet aber nicht schon, wie wir hier politisch handeln sollen.',service:'Der Dienst gilt auch Gegnern. Zugleich bleiben die Menschen, die unter der bisherigen Ordnung leiden, unsere Nächsten.',order:'Ordnung kann schützen und selbst Unrecht fortsetzen. Luthers scharfe Forderung nach Eingreifen kann wiederum Gewalt legitimieren.',revolt:'Berechtigte Forderungen erlauben nicht jedes Mittel. Auch die Gewalt der Obrigkeit muss sich an ihren Folgen für Menschen prüfen lassen.'};
export function lutherReflection(value){return 'Du findest '+lutherNames[value.helpful]+' hilfreich und siehst bei '+lutherNames[value.tension]+' eine Spannung. '+lutherLimits[value.tension];}
export function pathReflection(g){const c=g.chapter5,out=[openingLabels[c.openingPath]+': Hier hast du deinen Weg aufgenommen.'];
 if(c.firstAction)out.push(chapterFiveChoices.ch5First.options.find(o=>o.id===c.firstAction).text);
 if(c.negotiationCondition)out.push('Deine Verhandlungsbedingung: '+chapterFiveChoices.ch5Condition.options.find(o=>o.id===c.negotiationCondition).text);
 if(c.communityCounsel)out.push('Dein Rat an den Prediger: '+chapterFiveChoices.ch5Counsel.options.find(o=>o.id===c.communityCounsel).text);
 if(c.prisonerDecision)out.push('Du hast über den Gefangenen entschieden: '+chapterFiveChoices.ch5Prisoner.options.find(o=>o.id===c.prisonerDecision).text);
 if(c.finalAction)out.push('Als die Truppen kamen: '+availableFinalActions(c).find(([id])=>id===c.finalAction)[1]);
 if(c.endWorldState)out.push(endLabels[c.endWorldState]+'.');return out.slice(0,6);
}
function recalls(g){const c=g.chapter4,lines=[];
 if(g.choiceTexts.initialFreedomInterpretation)lines.push(l('jakob','In der Taverne war dein erster Gedanke: '+g.choiceTexts.initialFreedomInterpretation+' Heute steht eine konkrete Handlung an.'));
 if(g.choices.playerDemand)lines.push(l('matthes','Unsere Forderung lautet noch immer: '+g.choices.playerDemand));
 const rel=g.perceptions||{},o=g.orientation||{};
 if(rel.anna?.includes('community_minded'))lines.push(l('anna','Du hast schon an die Gemeinde gedacht. Ich rechne mit deiner Hilfe, wenn heute Menschen zurückbleiben.'));
 else if(rel.anna?.includes('willing_to_resist'))lines.push(l('anna','Du hast schon einen Anspruch trotz des Verbots durchgesetzt. Heute will ich vorher hören, wer die Betroffenen schützt.'));
 else if(rel.anna?.includes('cautious'))lines.push(l('anna','Du hast einen Streit vermieden. Die fehlenden Vorräte sind dadurch nicht ersetzt. Auch ein vorsichtiger Weg braucht praktische Hilfe.'));
 if(g.chapter5.openingPath==='peasant_band')lines.push(l('konrad',rel.konrad?.includes('willing_to_resist')?'Du hast schon widersprochen. Jetzt traue ich darauf, dass du auch bei den Folgen dabeibleibst.':'Du bist bei uns. Welche Mittel du mittragen willst, muss ich trotzdem erst hören.'));
 else if(g.chapter5.openingPath==='negotiation')lines.push(l('peter',rel.peter?.includes('seeks_negotiation')?'Du hast schon nach einem Gesprächsweg gesucht. Ich möchte wissen, welche Zusage diesmal trägt.':'Wir reden weiter. Ich brauche von dir eine Grenze dessen, was wir dafür zusagen dürfen.'));
 else lines.push(l('jakob',(o.theological||0)>0?'Du hast die Auslegung schon geprüft. Heute muss sie sich an einem bedrohten Menschen bewähren.':'Der Streit um Freiheit wird jetzt ein Streit um ihre Folgen.'));
 if(g.chapter3.publicTone==='confrontational')lines.push(l('matthes','Unser anklagendes Blatt ist angekommen. Die Herrschaft hört unsere neue Bitte vor dem Hintergrund dieses Vorwurfs.'));
 else if(g.chapter3.printStrategy==='full')lines.push(l('matthes','Die vollständigen Artikel sind im Umlauf. Einige können unsere Forderung genauer nachlesen, statt nur Gerüchte weiterzugeben.'));
 if(g.chapter3.religiousInterpretation)lines.push(l('jakob','In Memmingen hast du die religiöse Begründung so gelesen: '+(g.choiceTexts.ch3Religion||g.chapter3.religiousInterpretation).replace(/[.!?]+$/, '')+'. Auch diese Deutung gehört jetzt auf den Prüfstand.'));
 if(g.choiceTexts.ch3Resistance)lines.push(l('matthes','Dein damaliger Weg war: '+g.choiceTexts.ch3Resistance+' Jetzt reagieren auch Menschen darauf, die diese Entscheidung nicht mitgetragen haben.'));
 if(c.lutherFreedomJudgmentEarly)lines.push(l('jakob','Dein früheres Urteil zu Luther bleibt dabei: '+(g.choiceTexts.ch4Early||c.lutherFreedomJudgmentEarly)));
 return lines;
}
export function prepareChapterFiveState(g,scene){
 g.chapter=5;g.notebook.unlocked=true;const c=g.chapter5;c.stage=scene.id.slice(4);c.step=0;c.phase='';c.selections=[];c.feedback=null;g.dialogue=null;g.interaction=null;syncConsequences(g);
 if(!c.openingPath){
  c.openingPath=deriveChapter5OpeningPath(g);
  // Carry an explicitly agreed limit into action, rather than only into the archive.
  c.limitsViolence ||= g.chapter4.handoff?.limitsViolence===true;
 }
 const start=(lines,next='ready')=>{g.dialogue={lines,index:0,after:'chapter-five',context:next};};
 const stage=c.stage;
 const prisoner=c.duesAction==='detain_messenger'?'Den Boten vom Wagen habt ihr noch immer bei euch.':'Nach dem Zusammenstoß haben andere Bauern einen Amtsboten festgehalten. Er bestreitet, den ersten Schlag geführt zu haben.';
 const dialogues={
 peasant_camp:[l('konrad','Heute gehen wir zum Amtshaus. Das Korn und die Abgaben dürfen nicht einfach weiter abgeführt werden.'),l('matthes','Einige sichern die Vorräte. Andere haben von Truppen auf der Straße gehört.'),l('band1','Wir brauchen Menschen, die mitgehen, und Menschen, die hier Versorgung organisieren.'),...recalls(g)],
 dues_cart:[l('envoy','Aus dem Weg. Das ist Eigentum des Herrn.'),l('konrad','Das war gestern noch unser Korn.'),l('matthes','Das Dorf liegt hinter uns. Wer den Wagen zurückbringt, muss auch erklären, was mit seinem Boten geschieht.')],
 supply:[l('matthes','Hier warten Menschen, die nicht kämpfen. Manche brauchen Essen, andere Hilfe für den Rückweg.'),l('band1','Wenn alle zum Amtshaus gehen, bleibt niemand bei ihnen. Was übernimmst du jetzt?')],
 limit_violence:[l('konrad','Und wenn sie angreifen? Sollen wir dann nur zuschauen?'),l('band1','Wir können vorher festhalten: kein Angriff auf Menschen, die keine Gefahr darstellen. Sonst entscheidet im Gedränge jeder allein.'),l('konrad','Ich trage diese Grenze mit. Ob wir sie unter Druck halten, müssen wir erst zeigen.')],
 negotiation_room:[l('overseer',c.firstAction==='delegation'?'Ihr kommt aus dem Haufen. Soll dieses Gespräch einen neuen Weg öffnen oder nur Zeit für die Blockade gewinnen?':'Die Lage hat sich verändert. Wenn ihr verhindert, dass weitere Leute sich dem Haufen anschließen, kann über einzelne Beschwerden gesprochen werden.'),l('peter','Also sollen wir zuerst gehorchen und danach hoffen.'),l('anna','Oder wir schaffen Zeit, bevor noch mehr Menschen hineingezogen werden.'),...(c.firstAction==='delegation'?[l('konrad','Wir kommen mit Forderungen. Über die anderen im Haufen könnt ihr nicht einfach durch uns verfügen.')]:recalls(g))],
 negotiation_effect:[l('overseer',chapterFiveChoices.ch5Condition.options.find(o=>o.id===c.negotiationCondition)?.reaction||'Der Entwurf bleibt offen.'),l('anna','Unsere Bedingung ist ausgesprochen. Ob daraus eine Zusage wird, hängt auch von den Ereignissen draußen ab.')],
 theological_council:[l('preacher','Draußen fragen sie mich, ob sie Widerstand leisten dürfen.'),l('jakob','Und was antwortest du?'),l('preacher','Wenn ich das wüsste, hätte ich euch nicht gerufen.'),l('anna','Dann sagt wenigstens nichts, das andere für euch mit Blut bezahlen.'),...recalls(g)],
 community_counsel:[l('preacher','Wir haben die Aussagen geprüft. Aber draußen warten Menschen. Was soll ich ihnen sagen?')],
 churchyard_conflict:[l('preacher','Die einen sagen: Wer Gewalt mit Gottes Wort rechtfertigt, macht aus dem Evangelium eine Waffe.'),l('jakob','Die anderen antworten: Wer nur von Ordnung redet, verlangt am Ende immer Gehorsam von denen, die leiden.'),l('jakob','Beide berufen sich auf den Glauben. Aber sie fürchten etwas anderes.'),...recalls(g)],
 escalation_message:[l('narrator',{peasant_band:'Ein Verletzter wird zum Lager gebracht. Er wird gestützt. Du folgst ihnen in einen freien Raum am Dorf, wo Hilfe möglich ist.',negotiation:'Mitten im Gespräch kommt eine Nachricht vom Weg. Die Bedingung im Entwurf gilt weiter; die Ereignisse draußen haben nicht darauf gewartet.',theological_council:'Die Tür öffnet sich. Matthes bringt einen Bericht vom Ortsrand.',religious_conflict:'Menschen kommen vom Ortsrand zurück. Die streitenden Gruppen wenden sich ihnen zu.'}[c.openingPath]),l('matthes','Es hat einen Zusammenstoß gegeben. Jeder erzählt es anders. Aber einer liegt schwer verletzt.'),l('jakob','Bevor wir Schuld zuschreiben, müssen wir unterscheiden, was wir wissen und was wir nur vermuten.')],
 prisoner_scene:[l('narrator',prisoner),l('konrad','Wenn wir ihn laufen lassen, kommt er mit Soldaten zurück.'),l('anna','Und wenn wir ihn festhalten, was wird dann aus uns?'),l('envoy','Ich habe Abgaben eingetrieben. Das macht mich nicht zum Urheber jedes Unrechts.'),l('jakob','Dann ist jetzt die Frage, was ihr mit Macht macht, wenn ihr sie selbst habt.')],
 neighbor_love:[l('jakob','Damals haben wir über den Dienst am Nächsten gesprochen.'),l('konrad','Der da ist nicht mein Nächster.'),l('anna','Wer entscheidet das?'),l('jakob','Luthers Freiheit vor Gott hebt den Dienst nicht auf. Hier müssen wir fragen, ob er auch dem Gegner gilt.')],
 internal_debate:[l('konrad','Wenn wir jedes Mal zurückweichen, sobald sie drohen, hat sich nichts verändert.'),l('peter','Wenn wir weitergehen, zahlen vielleicht Menschen dafür, die nie gefragt wurden.'),l('jakob','Eine gerechte Sache macht nicht automatisch jedes Mittel gerecht.'),l('band1','Und wer immer nur nach dem richtigen Mittel sucht, wartet vielleicht so lange, bis andere entschieden haben.')],
 troops_approach:[l('matthes','Sie kommen.'),l('peter','Wie viele?'),l('matthes','Mehr als wir aufhalten können.'),...(c.communityCounsel?[l('preacher',counselLines[c.communityCounsel])]:[]),...(g.chapter4.centralRisk?[l('jakob','Du hast zuvor diese Gefahr besonders gesehen: '+(g.choiceTexts.ch4Risk||g.chapter4.centralRisk)+'. Jetzt musst du unter unvollständigem Wissen handeln.')]:[]),...(g.chapter4.lutherHarshTextJudgment?[l('jakob','Dein Urteil über Luthers schärfere Schrift war: '+(g.choiceTexts.ch4HarshJudgment||g.chapter4.lutherHarshTextJudgment)+'. Auch die Mittel unserer eigenen Seite brauchen Prüfung.')]:[])],
 end:[l('jakob','Wir haben lange gefragt, was wir tun dürfen.'),l('anna','Und jetzt?'),l('jakob','Jetzt müssen wir auch fragen, wofür wir Verantwortung tragen.')]
 };
 if(dialogues[stage])start(dialogues[stage]);
 if(stage==='limit_violence')c.limitsViolence=true;
 if(stage==='action_effect'){resolveChapterFiveOutcomes(g);start(actionConsequence(g));}
 if(stage==='after_crisis')start([l('narrator',endLabels[c.endWorldState]+'. Der vertraute Dorfplatz trägt die Folgen.'),l('anna',outcomeTexts.civilian[c.civilianOutcome]),l('peter',outcomeTexts.negotiation[c.negotiationOutcome]),l('jakob','Schutz und politischer Erfolg sind nicht dasselbe. Dass einige in Sicherheit sind, hebt das erlittene Unrecht nicht auf.'),l('anna','Und wer fortmusste, braucht weiter Nahrung, Unterkunft und Menschen, die ihn aufnehmen.')]);
 if(stage==='konrad_news')start([l('matthes',outcomeTexts.konrad[c.konradOutcome]),l('peter','Das haben wir nicht allein bestimmt. Trotzdem gehört es jetzt zu dem Weg, an dem wir beteiligt waren.'),l('jakob','Das Gewissen ist keine Garantie für einen guten Ausgang. Wir müssen auch fragen, welche Schuld und welche Verantwortung unser Handeln hinterlässt.'),l('anna','Die nächste Aufgabe wartet bei den Menschen, die noch Hilfe brauchen.')]);
 if(stage==='chapter6'){c.completed=true;c.handoff=chapterSixHandoff(g);}
}
export function prepareChapterFive(scene){prepareChapterFiveState(state,scene);}
function actionConsequence(g){const c=g.chapter5,f=c.finalAction;
 const events={protected_retreat:'Du erinnerst die Gruppe an ihre zugesagte Grenze. Einige tragen Bedrohte mit zurück; andere bleiben und bestreiten, dass deine Grenze hier noch gilt.',stay_with_band:'Du bleibst beim Haufen. Die Linie hält nicht; Menschen werden auseinandergetrieben.',join_band:'Du gehst vom Gespräch zum Haufen. Am Amtshaus findet die Abordnung nun keine Gesprächspartner mehr.',protect_wounded:'Ihr stützt Verletzte auf dem Rückweg. Andere bleiben beim Haufen; die Versorgung bringt euch aus ihrer Linie.',evacuate_civilians:'Anna führt Familien aus dem Dorfbereich. Nicht alle können ihre Vorräte mitnehmen.',protect_people:'Jakob geht mit dir zu den Bedrohten. Die Beratung wird zur konkreten Hilfe.',joint_protection:'Einige aus beiden Gruppen tragen gemeinsam Menschen zurück. Andere weigern sich, mit der Gegenseite zu gehen.',urge_retreat:'Du rufst zum Rückzug. Einige folgen, andere bleiben, weil sie das Zurückweichen für Verrat halten.',defensive_only:'Ihr haltet nur eine Verteidigungslinie. Unter Druck bleibt umstritten, welcher Schritt schon ein Angriff ist.',last_delegation:'Die Abordnung geht den Truppen entgegen. Der Befehlshaber will erst hören, wer für die Zusagen einsteht.',negotiate_village_protection:'Die Abordnung bittet um Schutz für das Dorf. Dafür verlangt die Herrschaft eine Zusage, dass niemand den Haufen weiter unterstützt.',mediate:'Du suchst einen Vermittler. Auf beiden Seiten sind noch Menschen zum Gespräch bereit; ihre Gruppen folgen ihnen nicht geschlossen.',public_religious_warning:'Du widersprichst öffentlich der Behauptung, Gewalt sei unmittelbar Gottes Auftrag. Einige hören zu, andere gehen weiter.',revise_counsel:'Du sprichst deinen früheren Rat erneut aus und benennst seine Grenze. Der Prediger steht neben dir; nicht alle hören die Korrektur.',support_one_group:'Du stellst dich zu einer Gruppe. Die andere geht fort. Eine gemeinsame Antwort kommt nicht mehr zustande.',reject_divine_certainty:'Der Prediger verzichtet auf die Behauptung, eine Seite verkörpere Gottes Willen. Der politische Streit ist damit noch nicht beigelegt.',separate_faith_and_strategy:'Du trennst die Glaubensüberzeugung von der Strategie und rufst zum Rückzug. Einige können nun zurückgehen, ohne ihren Glauben widerrufen zu müssen.'};
 const prisoner={release:'Der Bote ist frei. Seine Meldung erreicht die Herrschaft; eine Rückkehr mit Truppen war möglich, aber nicht sicher.',protect_detention:c.civilianOutcome==='many_protected'?'Ihr nehmt den Gefangenen beim Rückweg mit. Zwei Menschen übernehmen seinen Schutz.':'Der Gefangene wartet auf Schutz, während die Gruppe auseinandergeht. Anna fordert, dass jemand bei ihm bleibt.',hand_to_council:c.endWorldState==='community_fragmented'?'Der Rat verliert sein gemeinsames Mandat. Die Übergabe garantiert nun keine anerkannte Entscheidung mehr.':'Der Rat übernimmt den Boten und hält die Entscheidung fest. Das Mandat muss weiter von der Gemeinde getragen werden.',bargaining_leverage:'Die Herrschaft fordert seine Freilassung vor weiteren Gesprächen. Das Druckmittel verschärft zugleich ihre Reaktion.'};
 return [l('narrator',events[f]),l('anna','Wir können nicht zugleich überall sein. Wer jetzt mitgeht, fehlt an einem anderen Ort.'),l('narrator',prisoner[c.prisonerDecision]),...(c.communityCounsel?[l('preacher',counselLines[c.communityCounsel])]:[]),l('matthes','Einige kommen zurück. Von anderen haben wir noch keine Nachricht.'),l('jakob','Der Streit um die Forderungen bleibt. Unsere Entscheidung hat vor allem verändert, was jetzt mit Menschen geschieht.')];
}
const choiceAt={peasant_camp:'ch5First',dues_cart:'ch5Dues',negotiation_room:'ch5Condition',community_counsel:'ch5Counsel',prisoner_scene:'ch5Prisoner',neighbor_love:'ch5Neighbor',freedom_after_action:'ch5Freedom'};
export function chapterFiveChoiceId(stage){return choiceAt[stage];}
const nextStage={intro:null,supply:'escalation_message',limit_violence:'escalation_message',negotiation_effect:'escalation_message',theological_council:'theological_arguments',churchyard_conflict:'polarization_analysis',escalation_message:'three_reports',three_reports:'prisoner_scene',neighbor_love:'religion_functions',religion_functions:'luther_balance',luther_balance:'internal_debate',internal_debate:'troops_approach',action_effect:'after_crisis',after_crisis:'konrad_news',konrad_news:'path_reflection',path_reflection:'freedom_after_action',end:'chapter6'};
export function chapterFiveNext(stage,g=state){return stage==='intro'?{peasant_band:'peasant_camp',negotiation:'negotiation_room',theological_council:'theological_council',religious_conflict:'churchyard_conflict'}[g.chapter5.openingPath]:nextStage[stage];}
export function chapterFiveAction(action,target){
 if(action==='ch5-start'){go('intro');return true;}
 if(state.chapter!==5)return false;
 if(action==='dialogue-next'&&state.dialogue?.after==='chapter-five'){const done=advanceDialogue();if(done&&done.context!=='ready')go(done.context);return true;}
 if(!action.startsWith('ch5-'))return false;
 const v=c(),s=v.stage,id=target.dataset.item;
 if(action==='ch5-next'){const next=chapterFiveNext(s);if(next)go(next);return true;}
 if(action==='ch5-choose'){
  const key=choiceAt[s],def=chapterFiveChoices[key],o=def?.options.find(o=>o.id===target.dataset.option);if(!o)return true;
  state.choices[key]=o.id;state.choiceTexts[key]=o.text;v[def.field]=o.id;syncConsequences(state);
  const next=key==='ch5First'?{stop_dues:'dues_cart',support_supply:'supply',delegation:'negotiation_room',limit_violence:'limit_violence'}[o.id]:{ch5Dues:'escalation_message',ch5Condition:'negotiation_effect',ch5Counsel:'escalation_message',ch5Prisoner:'neighbor_love',ch5Neighbor:'religion_functions',ch5Freedom:'end'}[key];
  if(def.reflective)talk([l(key==='ch5Counsel'?'preacher':key==='ch5Condition'?'overseer':key==='ch5Prisoner'?'anna':'jakob',o.reaction)],next);
  else {const count=(v.attempts[key]||0)+1;v.attempts[key]=count;const done=o.id===def.solution||count>=2;v.feedback={text:o.reaction+(count>=2&&o.id!==def.solution?' Gemeinsam halten wir fest: '+def.options.find(o=>o.id===def.solution).reaction:''),next:done?next:null,submitted:o.text};if(done)v.resolved[key]=true;}
 }
 if(action==='ch5-feedback'){const f=v.feedback;v.feedback=null;if(f?.next)go(f.next);else if(s==='theological_arguments'){v.phase='';v.step++;}else if(s==='three_reports'){v.step++;}else if(s==='polarization_analysis'){v.phase='';v.step++;}return true;}
 if(action==='ch5-supply'&&['food','material','wounded'].includes(id)){v.supplyAction=id;talk([l('matthes',{food:'Du bringst Nahrung zu denen, die im Lager bleiben. Der Vorrat reicht für diesen Aufbruch, nicht für einen langen Zug.',material:'Du legst Tücher und Trageholz bereit. Andere nehmen sie mit; Menschen, die nicht kämpfen, tragen jetzt die Versorgung.',wounded:'Du bleibst bei denen, die Hilfe brauchen. Für den Weg zum Amtshaus fehlen dadurch Hände.'}[id])],'escalation_message');}
 if(action==='ch5-field'){
  if(s==='theological_arguments'&&!v.feedback){const a=theologicalArguments[v.step];if(!a||!['help','limit'].includes(id))return true;v.theologicalCounsel[a[0]]||={};v.theologicalCounsel[a[0]][v.phase==='limit'?'limit':'help']=id;const chosen=v.phase==='limit'?'limit':'help';if(chosen==='help')v.phase='limit';else {const entry=v.theologicalCounsel[a[0]];v.feedback={text:'Du betonst: '+(entry.help==='help'?a[2]:theologicalAlternatives[a[0]][0])+' Als Grenze hältst du fest: '+(entry.limit==='limit'?a[3]:theologicalAlternatives[a[0]][1])+' Auch die andere Perspektive bleibt zu prüfen: '+(entry.help==='help'?theologicalAlternatives[a[0]][0]:a[2])+' '+(entry.limit==='limit'?theologicalAlternatives[a[0]][1]:a[3]),submitted:a[1]};}}
  if(s==='polarization_analysis'&&!v.feedback){const key=['order','justice'][v.step];if(!key)return true;v.polarizationAnalysis[key]||={};v.polarizationAnalysis[key][v.phase==='blind'?'overlooked':'danger']=id;if(v.phase!=='blind')v.phase='blind';else v.feedback={text:key==='order'?'Die Sorge um Ordnung sieht Gewalt und Selbstermächtigung. Sie kann übersehen, dass auch eine bestehende Ordnung Unrecht hervorbringt.':'Die Sorge um Gerechtigkeit sieht Unterdrückung. Sie kann übersehen, dass religiöse Gewissheit die eigenen Mittel jeder Kritik entzieht.'};}
 }
 if(action==='ch5-task-next'){if(s==='theological_arguments'&&v.step===4)go('community_counsel');if(s==='polarization_analysis'&&v.step===2)go('escalation_message');if(s==='three_reports'&&v.step===5)go('prisoner_scene');}
 if(action==='ch5-reports-read')v.phase='assessment';
 if(action==='ch5-begin-arguments'&&s==='theological_arguments')v.phase='help';
 if(action==='ch5-report'&&s==='three_reports'&&!v.feedback){const fact=reportFacts[v.step];if(!fact||!['certain','uncertain'].includes(id))return true;v.reportAnswers[fact[0]]=id;v.violenceReportsAssessment[fact[2]].push(fact[0]);v.violenceReportsAssessment[fact[2]]=[...new Set(v.violenceReportsAssessment[fact[2]])];v.feedback={text:(id===fact[2]?'Deine Einordnung wird durch die Berichte gestützt. ':'Deine Einordnung braucht eine Grenze. ')+fact[3],submitted:fact[1]};}
 if(action==='ch5-function'){const ids=v.religionFunctions.strongest;if(v.phase==='risk')v.religionFunctions.dangerousWhenAbsolute=id;else if(ids.includes(id))ids.splice(ids.indexOf(id),1);else {if(ids.length===2)ids.shift();ids.push(id);}}
 if(action==='ch5-functions-next'){if(v.phase!=='risk'&&v.religionFunctions.strongest.length===2)v.phase='risk';else if(v.phase==='risk'&&v.religionFunctions.dangerousWhenAbsolute)talk([l('jakob',functionReflection(v.religionFunctions))],'luther_balance');}
 if(action==='ch5-luther'){v.lutherTension[v.phase==='tension'?'tension':'helpful']=id;}
 if(action==='ch5-luther-next'){if(v.phase!=='tension'&&v.lutherTension.helpful)v.phase='tension';else if(v.phase==='tension'&&v.lutherTension.tension)talk([l('jakob',lutherReflection(v.lutherTension))],'internal_debate');}
 if(action==='ch5-debate'){v.internalDebate[v.phase==='danger'?'mostDangerousAbsolute':'strongestArgument']=id;}
 if(action==='ch5-debate-next'){if(v.phase!=='danger'&&v.internalDebate.strongestArgument)v.phase='danger';else if(v.phase==='danger'&&v.internalDebate.mostDangerousAbsolute)talk([l('jakob',debateArguments.find(a=>a[0]===v.internalDebate.mostDangerousAbsolute)[2])],'troops_approach');}
 if(action==='ch5-final'&&availableFinalActions(v).some(([key])=>key===id)){v.finalAction=id;state.choices.ch5Final=id;state.choiceTexts.ch5Final=availableFinalActions(v).find(([key])=>key===id)[1];syncConsequences(state);resolveChapterFiveOutcomes(state);go('action_effect');}
 return true;
}
