import { state } from './state.js';
import { sceneById, scenes } from '../data/scenes.js';
import { characters } from '../data/characters.js';
import { chapters } from '../data/chapters.js';
import { esc, button } from './ui.js';
export function sceneView() {
  const scene = sceneById[state.scene], current = state.dialogue?.lines[state.dialogue.index];
  const interactive = !state.dialogue && !state.interaction && ['explore', 'conversations'].includes(scene.kind);
  return `<header class="game-header"><button class="wordmark" data-action="home" aria-label="Zum Startbildschirm">1525<span>Zwischen Freiheit und Aufruhr</span></button><div class="chapter-indicator"><span class="eyebrow">Kapitel 01</span><strong>${chapters[0].title}</strong></div><div class="header-actions">${button('<img src="assets/ui/book.svg" alt=""> <span>Notizbuch</span>', 'notebook', `class="book-button" ${!state.notebook.unlocked ? 'disabled title="Wird nach der Freiheitsachse geöffnet"' : ''}`)}${button('☰ <span class="sr-only">Spielmenü</span>', 'menu', 'class="quiet menu-button"')}</div></header><main class="game-layout ${scene.kind === 'sorting' ? 'sorting-layout' : ''}"><section class="stage" aria-label="Taverne am Abend"><div class="stage-caption"><span class="eyebrow">${chapters[0].season} · Taverne</span><h1>${scene.title}</h1></div><div class="characters">${['peter', 'jakob', 'anna'].map(id => {
    const character = characters[id], done = state.progress.conversations.includes(id), emotion = current?.speaker === id ? current.emotion || 'neutral' : scene.emotions?.[id] || 'neutral';
    return `<button class="character ${current?.speaker === id ? 'speaking' : ''}" data-action="character" data-character="${id}" data-emotion="${emotion}" ${interactive ? '' : 'disabled'} aria-label="Mit ${character.name} sprechen${done ? ', Gespräch geführt' : ''}"><img src="${character.asset}" alt="${character.name}, ${character.states[emotion]}"><span class="character-label">${character.name} ${done && scene.kind === 'conversations' ? '<span class="visited">✓</span>' : '<span aria-hidden="true">＋</span>'}</span></button>`;
  }).join('')}</div><div class="table-props">${button('<span aria-hidden="true">♧</span><span>Krug</span>', 'prop-mug', `class="prop mug" ${interactive && scene.kind === 'explore' ? '' : 'disabled'}`)}${scene.kind === 'explore' ? button('<span class="paper-lines" aria-hidden="true">≋</span><span>Flugblatt</span>', 'flyer', `class="prop flyer ${state.progress.flyerUnlocked ? 'unlocked' : ''}" ${state.progress.flyerUnlocked && interactive ? '' : 'disabled'}`) : '<div class="paper-decoration" aria-hidden="true">≋</div>'}${button('<span class="candle-flame" aria-hidden="true"></span><span>Kerze</span>', 'prop-candle', `class="prop candle" ${interactive && scene.kind === 'explore' ? '' : 'disabled'}`)}</div><div class="stage-bottom"><span>${scene.kind === 'conversations' ? `${state.progress.conversations.length} / 3 Gespräche` : 'Ein historisch-theologisches Adventure'}</span><span>${Math.min(scenes.indexOf(scene) + 1, 8)} / 8 Stationen</span></div></section><div id="interaction" class="interaction"></div></main><footer class="game-footer"><span>Freiheit beginnt mit einer Frage.</span><span id="save-status">Fortschritt wird lokal gespeichert</span></footer>`;
}
