import { sortingGames, puzzles } from '../../data/minigames.js';
import { state } from '../state.js';
import { esc, button } from '../ui.js';
export function puzzleView(id) {
  const game = puzzles[id], selected = state.minigames.puzzle;
  return `<section class="puzzle-panel task-panel"><div class="task-heading"><p class="eyebrow">Annas Frage</p><h2>${game.title}</h2><p>${esc(game.instruction)}</p></div><div class="task-scroll puzzle-grid"><div class="sequence" aria-label="Deine Reihenfolge">${Array.from({length:4}, (_, index) => {
    const part = game.parts.find(p => p.id === selected[index]);
    return `<div class="sequence-slot"><span class="step-number">${index + 1}</span><p>${part ? esc(part.text) : 'Karte auswählen …'}</p>${part ? `<div class="sequence-controls">${button('↑', 'puzzle-move', `data-index="${index}" data-direction="-1" aria-label="Karte ${part.id} nach vorn" ${index === 0 ? 'disabled' : ''}`)}${button('↓', 'puzzle-move', `data-index="${index}" data-direction="1" aria-label="Karte ${part.id} nach hinten" ${index === selected.length - 1 ? 'disabled' : ''}`)}${button('×', 'puzzle-part', `data-part="${part.id}" aria-label="Karte ${part.id} entfernen"`)}</div>` : ''}</div>`;
  }).join('')}</div><div class="puzzle-parts">${game.parts.map(part => `<button data-action="puzzle-part" data-part="${part.id}" aria-pressed="${selected.includes(part.id)}" ${selected.length >= 4 && !selected.includes(part.id) ? 'disabled' : ''}><span class="choice-letter">${part.id}</span><span>${esc(part.text)}</span></button>`).join('')}</div></div><div class="panel-actions">${button('Auswahl leeren', 'puzzle-reset', 'class="quiet"')}${button('Reihenfolge prüfen →', 'puzzle-check', `class="primary" ${selected.length !== 4 ? 'disabled' : ''}`)}</div></section>`;
}
export function axisView(id, selected = null) {
  const game = sortingGames[id], assigned = Object.keys(state.minigames.axis).length, current = game.cards.find(c => c.id === selected);
  return `<section class="axis-panel task-panel"><div class="task-heading"><div class="game-heading"><h2>${game.title}</h2><span class="count">${assigned} / ${game.cards.length}</span></div><p>${game.instruction}</p><p class="muted">Karte ziehen oder antippen, dann auf der Achse platzieren. Mit dem Regler lässt sich die Position ändern.</p></div><div class="axis-workspace"><div class="axis-labels"><span>${game.left}</span><span>${game.right}</span></div><button class="axis-rail" data-action="axis-position" aria-label="Ausgewählten Begriff auf der Achse platzieren" ${!selected ? 'disabled' : ''}><span class="axis-guide" aria-hidden="true">← ──────────────────── →</span>${current && state.minigames.axis[current.id] !== undefined ? `<span class="axis-marker" style="left:${state.minigames.axis[current.id]}%" aria-hidden="true"></span>` : ''}</button><div class="axis-control"><label for="axis-range">${current ? esc(current.text) : 'Zuerst eine Karte auswählen'} <output id="axis-value">${current ? (state.minigames.axis[current.id] ?? 50) + ' %' : ''}</output></label><input id="axis-range" type="range" min="0" max="100" step="1" value="${current ? state.minigames.axis[current.id] ?? 50 : 50}" ${!selected ? 'disabled' : ''} aria-label="Position des ausgewählten Begriffs auf der Freiheitsachse"></div></div><div class="task-scroll"><div class="card-bank">${game.cards.map(card => `<button class="axis-card ${selected === card.id ? 'selected' : ''}" data-action="axis-card" data-card="${card.id}" aria-pressed="${selected === card.id}"><span>${esc(card.text)}</span><small>${state.minigames.axis[card.id] !== undefined ? state.minigames.axis[card.id] + ' %' : '＋'}</small></button>`).join('')}</div></div><div class="panel-actions">${button('Zuordnung leeren', 'axis-reset', 'class="quiet"')}${button('Zuordnung prüfen →', 'axis-check', `class="primary" ${assigned !== game.cards.length ? 'disabled' : ''}`)}</div></section>`;
}
export function checkAxis(id) { return sortingGames[id].cards.every(card => typeof state.minigames.axis[card.id] === 'number' && state.minigames.axis[card.id] >= card.range[0] && state.minigames.axis[card.id] <= card.range[1]); }
export function axisPosition(rail, clientX) { const rect = rail.getBoundingClientRect(); return Math.max(0, Math.min(100, Math.round((clientX - rect.left) / rect.width * 100))); }
