import { sortingGames, puzzles } from '../../data/minigames.js';
import { state } from '../state.js';
import { esc, button } from '../ui.js';
export function puzzleView(id) {
  const game = puzzles[id], selected = state.minigames.puzzle;
  return `<section class="puzzle-panel task-panel"><div class="task-heading"><p class="eyebrow">Annas Frage</p><h2>${game.title}</h2><p>${esc(game.instruction)}</p></div><div class="task-scroll puzzle-grid"><div class="sequence" aria-label="Deine Reihenfolge">${Array.from({length:4}, (_, index) => {
    const part = game.parts.find(p => p.id === selected[index]);
    return `<div class="sequence-slot"><span class="step-number">${index + 1}</span><p>${part ? esc(part.text) : 'Karte auswählen …'}</p>${part ? `<div class="sequence-controls">${button('↑', 'puzzle-move', `data-index="${index}" data-direction="-1" aria-label="Karte ${part.id} nach vorn" ${index === 0 ? 'disabled' : ''}`)}${button('↓', 'puzzle-move', `data-index="${index}" data-direction="1" aria-label="Karte ${part.id} nach hinten" ${index === selected.length - 1 ? 'disabled' : ''}`)}${button('×', 'puzzle-part', `data-part="${part.id}" aria-label="Karte ${part.id} entfernen"`)}</div>` : ''}</div>`;
  }).join('')}</div><div class="puzzle-parts">${game.parts.map(part => `<button data-action="puzzle-part" data-part="${part.id}" aria-pressed="${selected.includes(part.id)}" ${selected.length >= 4 && !selected.includes(part.id) ? 'disabled' : ''}><span class="choice-letter">${part.id}</span><span>${esc(part.text)}</span></button>`).join('')}</div></div><div class="panel-actions">${button('Auswahl leeren', 'puzzle-reset', 'class="quiet"')}${button('Reihenfolge prüfen →', 'puzzle-check', `class="primary" ${selected.length !== 4 ? 'disabled' : ''}`)}</div></section>`;
}
export function sortingView(id, selected = null) {
  const game = sortingGames[id], assignments = state.minigames.sorting;
  const assigned = game.cards.filter(card => assignments[card.id]).length;
  const cardView = card => `<button class="sort-card ${selected === card.id ? 'selected' : ''}" data-action="sort-card" data-card="${card.id}" aria-pressed="${selected === card.id}" aria-label="${esc(card.text)}${assignments[card.id] ? ', '+game.zones.find(zone=>zone.id===assignments[card.id]).title : ''}">${esc(card.text)}</button>`;
  const unassigned = game.cards.filter(card => !assignments[card.id]);
  return `<section class="sorting-panel task-panel"><div class="task-heading"><div class="game-heading"><h2>${esc(game.title)}</h2><span class="count">${assigned} / ${game.cards.length}</span></div><p>${esc(game.instruction)}</p><p class="muted">Karte ziehen oder antippen, dann den Zielbereich antippen.</p></div><div class="task-scroll sorting-workspace"><div class="sort-zones">${game.zones.map(zone=>`<section class="sort-zone" data-drop-zone="${zone.id}" data-zone="${zone.id}" aria-label="${esc(zone.title)}"><button id="sort-target-${zone.id}" class="sort-target" data-action="sort-target" data-zone="${zone.id}" aria-label="Ausgewählte Karte: ${esc(zone.title)}" ${!selected ? 'disabled' : ''}><strong>${esc(zone.title)}</strong><span>${esc(zone.subtitle)}</span></button><div class="sort-zone-cards">${game.cards.filter(card=>assignments[card.id]===zone.id).map(cardView).join('')}</div></section>`).join('')}</div>${unassigned.length ? `<div class="sort-bank" aria-label="Noch nicht zugeordnete Karten">${unassigned.map(cardView).join('')}</div>` : ''}</div><div class="panel-actions">${button('Zuordnung leeren','sort-reset','class="quiet"')}${button('Zuordnung prüfen','sort-check',`class="primary" ${assigned!==game.cards.length ? 'disabled' : ''}`)}</div></section>`;
}
export function checkSorting(id) {
  return sortingGames[id].cards.every(card => ['god','world'].includes(state.minigames.sorting[card.id]) && (card.boundary || state.minigames.sorting[card.id]===card.preferred));
}