import { sortingGames, puzzles } from '../../data/minigames.js';
import { state } from '../state.js';
import { esc, button } from '../ui.js';
export function puzzleView(id, feedback = '') {
  const game = puzzles[id];
  return `<section class="puzzle-panel"><p class="eyebrow">Annas Frage · Satzpuzzle</p><h2>${game.title}</h2><p>${game.instruction}</p><div class="sentence-slots">${['Grund', 'Folge'].map((label, index) => `<div><span class="eyebrow">${label}</span><p>${esc(game.parts.find(p => p.id === state.minigames.puzzle[index])?.text || 'Wähle einen Baustein …')}</p></div>`).join('')}</div><div class="puzzle-parts">${game.parts.map(part => `<button data-action="puzzle-part" data-part="${part.id}" aria-pressed="${state.minigames.puzzle.includes(part.id)}">${esc(part.text)}</button>`).join('')}</div><p class="feedback" role="status">${esc(feedback)}</p><div class="panel-actions">${button('Auswahl leeren', 'puzzle-reset', 'class="quiet"')}${button('Gedanken verbinden →', 'puzzle-check', `class="primary" ${state.minigames.puzzle.length !== 2 ? 'disabled' : ''}`)}</div></section>`;
}
export function axisView(id, feedback = '', selected = null) {
  const game = sortingGames[id];
  const assigned = Object.keys(state.minigames.axis).length;
  const card = item => `<button class="axis-card ${selected === item.id ? 'selected' : ''}" data-action="axis-card" data-card="${item.id}" aria-pressed="${selected === item.id}" aria-label="${esc(item.text)}, ${state.minigames.axis[item.id] ? game.zones.find(z => z.id === state.minigames.axis[item.id])?.label : 'noch nicht zugeordnet'}">${esc(item.text)}<span aria-hidden="true">⠿</span></button>`;
  return `<section class="axis-panel"><div class="game-heading"><div><p class="eyebrow">Gedanken ordnen · Freiheitsachse</p><h2>${game.title}</h2></div><span class="count">${assigned} / ${game.cards.length}</span></div><p>${game.instruction}</p><div class="axis-line" aria-hidden="true">Beziehung zu Gott <span>⟷</span> äußere Lebensverhältnisse</div><div class="axis-zones">${game.zones.map(zone => `<div class="axis-zone" data-zone="${zone.id}"><button class="zone-target" data-action="axis-zone" data-zone="${zone.id}" ${!selected ? 'aria-disabled="true"' : ''}><strong>${zone.label}</strong><span>${zone.subtitle}</span></button><div class="zone-cards">${game.cards.filter(c => state.minigames.axis[c.id] === zone.id).map(card).join('')}</div></div>`).join('')}</div><div class="card-bank" aria-label="Noch nicht zugeordnete Karten">${game.cards.filter(c => !state.minigames.axis[c.id]).map(card).join('')}</div><p class="feedback" role="status">${esc(feedback || (selected ? `${game.cards.find(c => c.id === selected).text}: Tippe jetzt auf einen Bereich.` : 'Alle Karten dürfen erneut verschoben werden.'))}</p><div class="panel-actions">${button('Zuordnung leeren', 'axis-reset', 'class="quiet"')}${button('Zuordnung besprechen →', 'axis-check', `class="primary" ${assigned !== game.cards.length ? 'disabled' : ''}`)}</div></section>`;
}
export function checkAxis(id) { const game = sortingGames[id]; return game.cards.every(card => card.accepted.includes(state.minigames.axis[card.id])); }
